version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    env_file: .env
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: BaoNhan123
      POSTGRES_DB: olpbe
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - strapi
    restart: always
#  pgadmin:
#    image: dpage/pgadmin4:latest
#    container_name: pgadmin
#    environment:
#      PGADMIN_DEFAULT_EMAIL: admin@admin.com
#      PGADMIN_DEFAULT_PASSWORD: admin
#    ports:
#      - "8080:80"
#    depends_on:
#      - postgres

volumes:
  postgres_data:

networks:
  strapi:
    name: Strapi
    driver: bridge
